server:
  port: 8080

logging:
  level:
    root: WARN
    org.springframework.web: Trace
    org.springframework.security: Trace

spring:
  redis:
    host: server.kaiy.vip
    port: 6379
    database: 3
  session:
    store-type: redis
  thymeleaf:
    cache: false
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, classpath:/templates/

